### ISSUE TITLE
Cannot read property subscribe of undefined

### ISSUE THREAD

**Issue by ticruz38** [haadcode/orbit-db#147]
I might vrery well have been wrong at some point,
When I'm trying to instantiate the Orbitdb document store, that error appear:

> ipfs-pubsub.js:16 Uncaught TypeError: Cannot read property 'subscribe' of undefined(…)

I am using ipfs-api, in the browser.

**Comment by haadcode** [comment]
Thanks for reporting the issue! Can you you try installing ipfs-api with `npm install @haad/ipfs-api` and then require it as `const ipfsApi = require('@haad/ipfs-api')` and let me know if that works?

We're in the process of releasing go-ipfs 0.4.5 and orbit-db is using the very latest (and experimental) version from a fork of ipfs-api.

Hope this helps!

**Comment by ticruz38** [comment]
Hi,
following your advice, I downloaded, ipfs-go version 0.4.5-dev and used the `@haad/ipfs-api` package
I now get a 500 server error

> POST http://localhost:5001/api/v0/pubsub/sub?discover=true&arg=restaurants&stream-channels=true 500 (Internal Server Error)

followed by

> pubsub.js:59 Uncaught TypeError: Cannot set property 'cancel' of undefined(…)

here is my code
```
const Orbitdb = require('orbit-db');
const IpfsApi = require('@haad/ipfs-api');

class IpfsStore {
    node: any;
    restaurant: any;
    constructor() {
        this.node = IpfsApi( 'localhost', '5001');
        const orbitdb = new Orbitdb(this.node);
        try {
            this.restaurant = orbitdb.docstore('restaurants');
        } catch (e) {
            console.log(e);
        }
    }
}
```

I somehow manage to use the docstore by passing { subscribe: false } in the config object

**Comment by haadcode** [comment]
Thanks @ticruz38 for the details! This helps. There's couple of things going on here but a bug you've just found is that the error message doesn't bubble up correctly (shouldn't be uncaught), so this is something we need to fix in orbit-db.

Passing `{ subscribe : false }` makes orbit-db to NOT replicate with other users. Your errors comes from the replication part of the code, so that makes sense. I'll look into to this.

Meanwhile, can you confirm which version of orbit-db you have installed? Do `npm ls orbit-db`. If you're not on `0.16.0-beta.x`, could you try and install 0.16.0-beta.1 and run it again (just to make sure you're on the latest version). 

If you're on `0.16.0-beta1`, then what you probably need is the 0.4.5-pre1 version of go-ipfs which is not officially released yet but can be downloaded from https://dist.ipfs.io/go-ipfs/v0.4.5-pre1. This build contains the pubsub feature that orbit-db depends on.

Oh, also, I think you have to do `this.node = new IpfsApi(...)` with the new keyword.

**Comment by ticruz38** [comment]
I did download the ipfs executable you sent to me, started the daemon, instantiate IpfsApi properly with the new keyword, I am on orbitdb 0.16.0-beta1, but still got the same errors. I can't use any of the store provided by orbitdb...

**Comment by haadcode** [comment]
Sorry for your troubles. There's one more thing to try and if that doesn't make it work, I'll need to take a deeper look as I fix things.

Did you run the go-ipfs binary with `--enable-pubsub-experiment` (probably not since I didn't advice so)? Try that and if it doesn't work, let me know.

**Comment by ticruz38** [comment]
Don't be sorry, I am thankful for your help and for the library!
Putting the flag on the daemon removed the errors above, sadly I'm unable to put data in the docstore but also in the kvstore, when I put something in the store I get this:

> OrbitDB.js:103 Uncaught (in promise) Error: Hash can't be null!(…)

**Comment by ticruz38** [comment]
well, my node_modules might have been spoil, with all the install workaround, cleaning them and make an npm install solve the problem. Thanks!

**Comment by gyuri-lajos** [comment]
I run into the same problem as I was upgrading ipfs and orbit-db to   "ipfs": "^0.30.1",
    "orbit-db": "^0.19.9"

Needed to have in ipfsConfig following the Orbitdb ToDo Example pattern

```javascript

 // Configuration for IPFS instance
    const ipfsConfig = {
        repo: '/conceptipedia/mobile/ipfs',
        EXPERIMENTAL: {
            pubsub: true,
        },
        config: {
            Addresses: {
                Swarm: [
                    // Use IPFS dev signal server
                    // '/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star',
                    '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/'
                ]
            },
        }
    }

```
